[Gor 64] Add Restaurant List Pages
GorillaEats/mobileapp pull request #22
Opened 2020-08-05 21:37 UTC by sarahannali

2020-08-06 01:08 UTC, kevo1ution requested changes

2020-08-06 01:08 UTC, kevo1ution commented on lib/data/models/search.dart
> +      print('before');
unecessary

2020-08-06 01:08 UTC, kevo1ution commented on lib/data/models/search.dart
> +  bool _listView = false;
why is there a need to keep track of whether or not listview is active in the search model?

2020-08-06 01:08 UTC, kevo1ution commented on lib/widgets/search/search.dart
> +  bool _activeBox;
I thought activelySearching is tracking whether or not we should show the autocomplete UI. Are you displaying the restaurant cards on the same animated container as the predictions results?

2020-08-06 01:08 UTC, kevo1ution commented on lib/widgets/search/search.dart
> +                            child: searchModel.listView
it seems that listView can be a part of the search state and no the model. will `searchModel.listView` be accessed outside of this widget?

2020-08-06 01:08 UTC, kevo1ution commented on lib/widgets/search/search.dart
> +              if (!_activeBox)
I thought we wanted to display with filter items when listview is active?

2020-08-06 01:08 UTC, kevo1ution commented on lib/widgets/search/search.dart
> +      height: MediaQuery.of(context).size.height - 116,
This height offset is absolute, how does this relate to the map cards? shouldn't map cards and the list button be in the same column?

2020-08-07 19:08 UTC, sarahannali commented on lib/data/models/search.dart
> +      print('before');
whoops

2020-08-07 19:13 UTC, sarahannali commented on lib/data/models/search.dart
> +  bool _listView = false;
yeah bc the animated container comes up and i need to know if to render the list view or the prediction results

2020-08-07 19:13 UTC, sarahannali commented on lib/widgets/search/search.dart
> +  bool _activeBox;
yes

2020-08-07 19:14 UTC, sarahannali commented on lib/widgets/search/search.dart
> +                            child: searchModel.listView
yeah it could be i can do that

2020-08-07 19:22 UTC, sarahannali commented on lib/widgets/search/search.dart
> +      height: MediaQuery.of(context).size.height - 116,
-116 bc the height of the search stuff at the top is about that many px and that way the column doesn't flow off the screen. map cards is in its own widget so I don't think i can put  them in the same column

2020-08-09 19:16 UTC, kevo1ution commented on lib/widgets/search/search.dart
> +      height: MediaQuery.of(context).size.height - 116,
I think you should make this button and map cards in the same column because in the future we will add more buttons like "locate me" , and we can just add it to the column in the order we want to show the buttons. It will also not need to have absolute positioning like "116". The downside is that this will be a little more challenging in decoupling the list button and the search.dart widget

2020-08-09 19:18 UTC, kevo1ution commented on lib/widgets/search/search.dart
> +  bool _activeBox;
I think we briefly talked about this, but the autocomplete UI and predictions results should be separate animated containers because the list view should still show the filters and the autocomplete doesn't. Also the when in the list view, you will still be able to click search to show autocomplete list, and when you click back button the autocomplete list disappears but leaves the list view still open

2020-08-09 19:20 UTC, kevo1ution commented on lib/data/models/search.dart
> +  bool _listView = false;
does this _listView state need to be in the model vs seach.dart widget?

2020-08-18 00:32 UTC, kevo1ution commented on lib/data/models/search.dart
> +  bool _listView = false;
This value should be initialized in the constructor and only declared here

2020-08-18 00:34 UTC, kevo1ution commented on lib/widgets/googlemaps.dart
> +
why is the zoomLevel added here, mapcards provides the defaultZoomLevel value and we want to reference one place for it

2020-08-18 00:34 UTC, kevo1ution commented on lib/widgets/googlemaps.dart
> +                        zoom: zoomLevel,
should be defaultZoomLevel

2020-08-18 00:37 UTC, kevo1ution commented on lib/widgets/restaurantcard.dart
> +  RestaurantCard({@required this.location, this.onMap});
is this.onMap required?

2020-08-18 00:37 UTC, kevo1ution commented on lib/widgets/search/search.dart
> +  bool _activeSearch;
maybe we don't need to change this, and leave how it was originally named

2020-08-18 00:40 UTC, kevo1ution commented on lib/widgets/search/search.dart
> +    return Consumer<SearchModel>(
this consumer is not necessary, just pass searchModel as an argument to the function in the build() function

2020-08-19 03:45 UTC, sarahannali commented on lib/widgets/restaurantcard.dart
> +  RestaurantCard({@required this.location, this.onMap});
yeah so it won't be updating the map if u have list view open bc so many things are visible on the page

2020-08-19 04:27 UTC, kevo1ution commented on lib/widgets/restaurantcard.dart
> +  RestaurantCard({@required this.location, this.onMap});
I mean should it be @required this.onMap?

2020-08-19 04:53 UTC, sarahannali commented on lib/widgets/restaurantcard.dart
> +  RestaurantCard({@required this.location, this.onMap});
oh yeah

2020-08-19 04:58 UTC, merged