[Gor 28] Show JSON Objects on Map
GorillaEats/mobileapp pull request #4
Opened 2020-06-16 00:33 UTC by sarahannali

2020-06-16 18:02 UTC, kevo1ution commented on lib/data/dbaccess.dart
> +Future<dynamic> getDBLocations() async {
It seems unecessary to have a `dbaccess.dart` file because we aren't accessing a database directly. Shouldn't we just move this to `nearbyplaces.dart`

2020-06-16 18:02 UTC, kevo1ution commented on lib/data/nearbyplaces.dart
> +part 'nearbyplaces.g.dart';
should `nearbyplaces.dart` be renamed to `locations.dart`, My assumption is that all of our location rest calls will go here, and the location class definition is here.

2020-06-16 18:02 UTC, kevo1ution commented on lib/data/nearbyplaces.dart
> +Future<List<Location>> getNearbyLocations() async {
Should this be a static function of Location?

2020-06-16 18:02 UTC, kevo1ution commented on lib/data/nearbyplaces.dart
> +  // ignore: omit_local_variable_types
is there a way to avoid this?

2020-06-16 18:02 UTC, kevo1ution commented on lib/data/nearbyplaces.dart
> +    final mapItem = cast<Map<String, dynamic>>(item);
why call an external function `cast`, can't we just cast it here directly, and we know that item is type `Map<String, dynamic>` so why do we need to check `x is T` and set to null? I think it is better to let it error if x is not T

2020-06-16 18:02 UTC, kevo1ution commented on lib/data/starbucks.json
> +[
We haven't determined the schema yet and this may be subject to change; is that okay?

2020-06-16 18:11 UTC, sarahannali commented on lib/data/starbucks.json
> +[
yeah we just need to update locations.g.dart with the new schema definitions

2020-06-16 18:16 UTC, sarahannali commented on lib/data/nearbyplaces.dart
> +  // ignore: omit_local_variable_types
i explicitly wrote the local variable type here because otherwise it automatically makes it a dynamic which means i would have to cast it to List<Location>

2020-06-17 18:25 UTC, kevo1ution commented on lib/data/locations.dart
> +    // ignore: omit_local_variable_types
Does this still apply?

2020-06-17 18:25 UTC, kevo1ution commented on lib/data/locations.dart
> +  static const connection = 'lib/data/starbucks.json';
Move member variables above the function prototypes

2020-07-01 03:21 UTC, sarahannali commented on lib/data/locations.dart
> +    // ignore: omit_local_variable_types
yeah the line below need its type explicitly listed or it becomes dynamic and I have to cast it

2020-07-01 19:34 UTC, kevo1ution requested changes

2020-07-01 19:34 UTC, kevo1ution commented on lib/data/locations.dart
> +    // ignore: omit_local_variable_types
This should be `final locations = <Location>[];` and you can delete that comment for ignoring the style

2020-07-01 19:34 UTC, kevo1ution commented on pubspec.yaml
> +  json_serializable: ^3.3.0
should be dev_dependency

2020-07-03 23:29 UTC, kevo1ution approved these changes

2020-07-03 23:31 UTC, merged