[Gor 31] Create Restaurant Page
GorillaEats/mobileapp pull request #7
Opened 2020-07-02 02:44 UTC by sarahannali

2020-07-02 03:19 UTC, kevo1ution requested changes

2020-07-02 03:19 UTC, kevo1ution commented on lib/data/foodItems.json
> +]
new line

2020-07-02 03:19 UTC, kevo1ution commented on lib/data/fooditems.dart
> +    final List<dynamic> categories = <dynamic>[];
you can just make it `final categories` and you won't have the lint problems

2020-07-02 03:19 UTC, kevo1ution commented on lib/main.dart
> +    return MaterialApp(title: 'Gorilla Eats', initialRoute: '/', routes: {
This will remove the map screen. Is this intended?

2020-07-02 03:19 UTC, kevo1ution commented on lib/widgets/categories.dart
> +Widget categoryHeader(String categoryName) {
will this function be used by other files? If not then I recommend making it a method in the _CategoriesState class.

2020-07-02 03:19 UTC, kevo1ution commented on lib/widgets/categories.dart
> +Widget createCategory(dynamic category) {
will this function be used by other files? If not then I recommend making it a method in the _CategoriesState class.

2020-07-02 03:19 UTC, kevo1ution commented on lib/screens/restaurant.dart
> +        children: <Widget>[
Is it necessary to do `<Widget>[...]` vs just `[]`? I notice you use this everywhere for children field

2020-07-02 03:19 UTC, kevo1ution commented on lib/widgets/foodcard.dart
> +Widget cardHeader(bool _isExpanded, FoodItem foodItem) {
will this function be used by other files? If not then I recommend making it a method in the _FoodCardState class

2020-07-02 03:19 UTC, kevo1ution commented on lib/widgets/foodcard.dart
> +Widget cardBody(FoodItem foodItem) {
will this function be used by other files? If not then I recommend making it a method in the _FoodCardState class

2020-07-02 03:19 UTC, kevo1ution commented on lib/widgets/foodcard.dart
> +    elevation: 0,
why is the elevation 0 versus using the default of 1.0?

2020-07-02 03:19 UTC, kevo1ution commented on lib/widgets/restaurant_banner.dart
> +                  child: Text('Taco Bell',
Is this information going to be configurable?

2020-07-02 03:19 UTC, kevo1ution commented on lib/widgets/restaurant_banner.dart
> +                  child: Text('Taco Bell',
Will we handle this in a seperate PR? how does this interact with your markers PR?

2020-07-02 03:19 UTC, kevo1ution commented on lib/widgets/restaurant_banner.dart
> +                  child: Text('Taco Bell',
Also this goes for the other information like address, open, etc.

2020-07-02 03:25 UTC, sarahannali commented on lib/main.dart
> +    return MaterialApp(title: 'Gorilla Eats', initialRoute: '/', routes: {
just so I could test it we need to properly implement routes but the google maps screen had no button to get the restaurant screen so I just rendered the restaurant screen directly

2020-07-02 03:28 UTC, sarahannali commented on lib/widgets/foodcard.dart
> +    elevation: 0,
because it leaves a shadow on the element that doesn't match the look in our figma

2020-07-02 03:28 UTC, sarahannali commented on lib/widgets/restaurant_banner.dart
> +                  child: Text('Taco Bell',
oh yeah i forgot to make this configurable let me do that

2020-07-02 03:31 UTC, sarahannali commented on lib/widgets/restaurant_banner.dart
> +                  child: Text('Taco Bell',
nvrmind

2020-07-03 01:28 UTC, kevo1ution commented on lib/main.dart
> +    return MaterialApp(title: 'Gorilla Eats', initialRoute: '/', routes: {
Maybe this change shouldn't be included in the PR? When we implement routes (should be a new ticket) we can make the appropriate changes here

2020-07-03 01:28 UTC, kevo1ution commented
there are merge conflicts

2020-07-03 04:59 UTC, sarahannali commented on lib/main.dart
> +    return MaterialApp(title: 'Gorilla Eats', initialRoute: '/', routes: {
kk

2020-07-03 05:03 UTC, sarahannali commented on lib/screens/restaurant.dart
> +        children: <Widget>[
yeah u can do both but I think the `<Widget>[...] ` version is standard bc its what the vscode autocompletes to and its whats shown in all their example apps on the website [ex](https://api.flutter.dev/flutter/widgets/Column-class.html)

2020-07-03 05:08 UTC, merged